export const testimonials = [
    {
      id: 1,
      image: "/images/testimonials/john-lisa.webp",
      name: "John M., Investor from USA",
      text: "The team guided me through the entire investment process. I now own a beautiful property in Istanbul.",
      rating: 5,
    },
    {
      id: 2,
      image: "/images/testimonials/john-lisa.webp",
      name: "Lina S., Family from Germany",
      text: "We relocated to Antalya with our kids. Everything was smooth and professional.",
      rating: 4,
    },
    {
      id: 3,
      image: "/images/testimonials/john-lisa.webp",
      name: "Rami A., Saudi Entrepreneur",
      text: "From legal consulting to paperwork, their service exceeded my expectations.",
      rating: 5,
    },
    {
      id: 4,
      image: "/images/testimonials/john-lisa.webp",
      name: "Chen L., Student from China",
      text: "They helped me find a university and student housing in Istanbul. Great experience!",
      rating: 4,
    },
    {
      id: 5,
      image: "/images/testimonials/john-lisa.webp",
      name: "Natalie P., UK Investor",
      text: "The citizenship process was handled smoothly and transparently.",
      rating: 5,
    },
    {
      id: 6,
      image: "/images/testimonials/john-lisa.webp",
      name: "Youssef K., Real Estate Buyer from Egypt",
      text: "I found a luxurious apartment in a prime location thanks to their local expertise.",
      rating: 4,
    },
    {
      id: 7,
      image: "/images/testimonials/john-lisa.webp",
      name: "Emily D., Freelancer from Canada",
      text: "Relocating to Turkey as a remote worker was easier than expected. Thank you!",
      rating: 5,
    },
    {
      id: 8,
      image: "/images/testimonials/john-lisa.webp",
      name: "Ahmet T., Retiree from Sweden",
      text: "Retirement in Turkey is wonderful. They helped me settle comfortably.",
      rating: 4,
    },
    {
      id: 9,
      image: "/images/testimonials/john-lisa.webp",
      name: "Sana R., Pakistani Student",
      text: "From visa to admission, their education team was so helpful!",
      rating: 5,
    },
    {
      id: 10,
      image: "/images/testimonials/john-lisa.webp",
      name: "Carlos F., Colombian Digital Nomad",
      text: "Fast service and reliable guidance for residency permit and apartment rental.",
      rating: 4,
    },
    {
      id: 11,
      image: "/images/testimonials/john-lisa.webp",
      name: "Zahra M., Entrepreneur from UAE",
      text: "They helped me register my startup and move to Istanbul with ease.",
      rating: 5,
    },
    {
      id: 12,
      image: "/images/testimonials/john-lisa.webp",
      name: "Lucas H., Software Engineer from Netherlands",
      text: "Their relocation service made the process seamless and efficient.",
      rating: 4,
    },
    {
      id: 13,
      image: "/images/testimonials/john-lisa.webp",
      name: "Fatima B., Investor from Morocco",
      text: "Highly recommend for anyone pursuing citizenship via real estate.",
      rating: 5,
    },
    {
      id: 14,
      image: "/images/testimonials/john-lisa.webp",
      name: "Mark J., Retiree from Australia",
      text: "Turkey is now my second home. Great support from this team!",
      rating: 4,
    },
    {
      id: 15,
      image: "/images/testimonials/john-lisa.webp",
      name: "Aisha T., Kuwaiti Client",
      text: "Loved the transparency and professionalism throughout the process.",
      rating: 5,
    },
    {
      id: 16,
      image: "/images/testimonials/john-lisa.webp",
      name: "Ivan D., Tech Founder from Russia",
      text: "Relocating my team to Istanbul was smooth thanks to their expert help.",
      rating: 4,
    },
    {
      id: 17,
      image: "/images/testimonials/john-lisa.webp",
      name: "Huda S., Medical Student from Jordan",
      text: "They guided me through university selection and housing. So grateful.",
      rating: 5,
    },
    {
      id: 18,
      image: "/images/testimonials/john-lisa.webp",
      name: "Musa N., Photographer from Kenya",
      text: "Their relocation package suited creatives like me perfectly.",
      rating: 4,
    },
    {
      id: 19,
      image: "/images/testimonials/john-lisa.webp",
      name: "Elena V., Lawyer from Spain",
      text: "I bought a second home in Bodrum. Everything was legally secure.",
      rating: 5,
    },
    {
      id: 20,
      image: "/images/testimonials/john-lisa.webp",
      name: "Samir P., Family from India",
      text: "Smooth transition for our family to settle in Izmir.",
      rating: 4,
    },
  ];
  